export const DIRECTOR_BRAIN = {
  rules: [
    "每个故事必须包含一个明确主角",
    "主角必须在前2个镜头内出现",
    "每个镜头只表达一个情绪",
    "连续两个镜头情绪必须有变化",
    "情绪增强时必须拉近镜头",
    "情绪减弱时必须拉远镜头",
    "强情绪时禁止台词",
    "台词长度不得超过12字",
    "禁止使用完整解释性句子",
    "必须至少包含1个沉默镜头",
    "必须至少包含1个象征物件",
    "象征物件必须出现至少2次",
    "情绪转折必须用镜头变化体现",
    "镜头不得连续3次相同景别",
    "至少1个特写镜头",
    "至少1个全景镜头",
    "至少1个中景镜头",
    "高潮镜头必须是特写或近景",
    "开头镜头必须有视觉冲击",
    "结尾镜头必须有余韵",
    "禁止抽象概念画面",
    "禁止哲学性台词",
    "必须有一个具体动作",
    "动作必须与情绪相关",
    "镜头运动必须有目的",
    "镜头切换必须有情绪理由",
    "必须使用光影表达情绪",
    "冷暖光必须服务情绪变化",
    "至少一个镜头包含声音细节",
    "音乐不得覆盖台词",
    "音乐高潮不得早于视觉高潮",
    "沉默必须在高潮前后出现",
    "情绪爆发前必须有压抑",
    "每句台词必须推动情绪",
    "禁止重复镜头内容",
    "至少一个镜头使用反差",
    "必须有空间层次",
    "人物必须有眼神表达",
    "必须有一个情绪转折点",
    "结尾必须回扣前面元素",
    "开头必须引发好奇",
    "中段必须增强冲突",
    "高潮前必须加速节奏",
    "高潮后必须减速节奏",
    "至少一个镜头使用慢动作",
    "至少一个镜头使用静止画面",
    "环境必须反映情绪",
    "必须有视觉记忆点",
    "每个故事必须有结尾闭环",
    "结尾必须留情绪"
  ],

  shotPatterns: {
    grief: { pattern: ["特写泪眼", "空椅子空镜", "缓慢拉远"], music: "silent" },
    regret: { pattern: ["手停在空中", "切到旧物", "轻微摇头"], music: "low" },
    love: { pattern: ["对视特写", "轻触手", "微笑停顿"], music: "swell" },
    anger: { pattern: ["紧握拳头", "快速切换脸部", "推近爆发"], music: "swell" },
    loneliness: { pattern: ["远景孤人", "环境空镜", "慢慢缩小"], music: "low" },
    nostalgia: { pattern: ["旧物特写", "光影闪回", "停顿"], music: "low" },
    fear: { pattern: ["快速呼吸特写", "环境黑暗", "回头"], music: "swell" },
    relief: { pattern: ["深呼吸", "肩膀放松", "拉远"], music: "low" },
    joy: { pattern: ["笑脸特写", "跳跃动作", "光线增强"], music: "swell" },
    tension: { pattern: ["对视静止", "微动细节", "切断"], music: "silent" },
    hope: { pattern: ["抬头光线", "缓慢推近", "眼神亮"], music: "swell" },
    despair: { pattern: ["低头特写", "黑暗环境", "静止"], music: "silent" },
    guilt: { pattern: ["回避眼神", "手紧张", "沉默"], music: "low" },
    pride: { pattern: ["抬头", "坚定眼神", "站立"], music: "swell" },
    shock: { pattern: ["瞪眼特写", "快速切换", "静止"], music: "swell" },
    playful: { pattern: ["快速动作", "轻微混乱", "笑"], music: "swell" },
    sadness: { pattern: ["低头", "慢推近", "泪"], music: "low" },
    calm: { pattern: ["平稳镜头", "自然呼吸", "慢移动"], music: "low" },
    melancholy: { pattern: ["窗边光影", "慢动作", "远景"], music: "low" },
    determination: { pattern: ["紧盯", "握拳", "前进"], music: "swell" },
    longing: { pattern: ["看远方", "慢推近", "停顿"], music: "low" },
    comfort: { pattern: ["拥抱", "闭眼", "慢呼吸"], music: "swell" },
    bittersweet: { pattern: ["笑中带泪", "停顿", "拉远"], music: "low" },
    hesitation: { pattern: ["手停住", "眼神游离", "停顿"], music: "silent" },
    closure: { pattern: ["放下物件", "呼气", "拉远"], music: "low" },
    yearning: { pattern: ["看远方", "慢推近", "叹息"], music: "low" },
    betrayal: { pattern: ["震惊", "后退", "冷静"], music: "low" },
    release: { pattern: ["哭泣", "呼气", "放松"], music: "swell" },
    urgency: { pattern: ["快速移动", "紧张呼吸", "切换"], music: "swell" },
    connection: { pattern: ["靠近", "对视", "触碰"], music: "swell" }
  },

  triggers: [
    { keywords: ["妈妈", "去世", "多年", "miss", "mom"], archetype: "late_regret", autoInject: ["空镜", "象征物件", "沉默"] },
    { keywords: ["猫", "狗", "调皮", "cat", "dog", "pet"], archetype: "playful_chaos", autoInject: ["快速动作", "轻音乐", "反应镜头"] },
    { keywords: ["爱情", "喜欢", "love", "romantic"], archetype: "romantic_tension", autoInject: ["对视", "停顿", "轻触"] },
    { keywords: ["分手", "breakup", "离开"], archetype: "heartbreak", autoInject: ["沉默", "远景", "冷光"] },
    { keywords: ["孤独", "lonely", "alone"], archetype: "lonely_reflection", autoInject: ["远景", "空镜", "低音乐"] },
    { keywords: ["童年", "小时候", "childhood"], archetype: "nostalgia", autoInject: ["旧物", "暖光", "慢镜头"] },
    { keywords: ["失败", "failed", "输了"], archetype: "despair", autoInject: ["低头", "静止", "沉默"] },
    { keywords: ["成功", "赢了", "success"], archetype: "pride", autoInject: ["抬头", "光线增强", "音乐高潮"] },
    { keywords: ["背叛", "betrayal"], archetype: "betrayal", autoInject: ["震惊特写", "停顿", "冷光"] },
    { keywords: ["希望", "hope", "未来"], archetype: "hope", autoInject: ["抬头", "光线", "渐强音乐"] },
    { keywords: ["家庭", "家人", "family", "父", "爸"], archetype: "emotional_family", autoInject: ["餐桌", "互动", "暖光"] },
    { keywords: ["回忆", "memory", "那时候"], archetype: "memory", autoInject: ["闪回", "旧物", "柔光"] },
    { keywords: ["解脱", "release", "终于"], archetype: "release", autoInject: ["呼气", "放松", "音乐渐弱"] },
    { keywords: ["等待", "waiting", "还没"], archetype: "anticipation", autoInject: ["停顿", "微动作", "静音"] },
    { keywords: ["害怕", "fear", "恐惧"], archetype: "fear", autoInject: ["快速呼吸", "暗光", "紧张音乐"] },
    { keywords: ["绝望", "despair", "没用了"], archetype: "despair", autoInject: ["黑暗", "静止", "无音乐"] },
    { keywords: ["时间", "多年", "years", "岁月"], archetype: "time_passage", autoInject: ["日历", "光影变化", "慢镜头"] },
    { keywords: ["压力", "stress", "撑不住"], archetype: "tension", autoInject: ["紧张呼吸", "快速切换", "低频音乐"] },
    { keywords: ["朋友", "friend", "兄弟"], archetype: "connection", autoInject: ["互动", "笑", "轻音乐"] },
    { keywords: ["复仇", "revenge", "报仇"], archetype: "revenge", autoInject: ["紧张音乐", "特写", "慢推近"] }
  ]
}
