"use server";

import { createClient } from "@/lib/supabase/server";
import { isValidUuid } from "@/lib/project-id";
import type { ActionResult } from "@/types";

export async function createProjectAction(input: {
  title: string;
  userId: string;
  language?: string;
  /** Director Mode: user-defined episode number. Null = no title card (Star Mode or no series). */
  episodeNumber?: number | null;
  /** Director Mode: user-defined series name. */
  seriesName?: string | null;
}): Promise<ActionResult<{ projectId: string }>> {
  try {
    console.log(
      "[CREATE PROJECT ENTRY]",
      JSON.stringify({ title: input.title, userId: input.userId, language: input.language ?? "en", episodeNumber: input.episodeNumber ?? null })
    );
    const supabase = createClient();

    // episode_number: only set if explicitly provided (Director Mode with series)
    // Star Mode and default Director Mode → default to 1 (avoids NOT NULL violation)
    const episodeNumber = input.episodeNumber ?? 1;
    console.log("[CREATE PROJECT] episode_number:", episodeNumber, "for user:", input.userId);

    const { data, error } = await supabase
      .from("projects")
      .insert({
        user_id: input.userId,
        title: input.title,
        language: input.language ?? "en",
        episode_number: episodeNumber,
        series_name: input.seriesName ?? null,
      })
      .select("id")
      .single();

    console.log("[DB INSERT]", JSON.stringify({ newProject: data, insertError: error }));

    if (error) {
      console.log("[CREATE PROJECT EXIT EARLY]", "insert returned error before success return");
      throw error;
    }
    return { success: true, data: { projectId: data.id as string } };
  } catch (e) {
    console.log("[CREATE PROJECT EXIT EARLY]", "caught exception in createProjectAction");
    return { success: false, error: e instanceof Error ? e.message : String(e) };
  }
}

function resolveProjectOwnerUserId(): string | null {
  const a = process.env.SCRIPTFLOW_DEMO_USER_ID?.trim();
  const b = process.env.SCRIPTFLOW_PROJECT_OWNER_USER_ID?.trim();
  // Prefer explicit owner ID over demo fallback when both exist.
  const id = b || a || "";
  return id && isValidUuid(id) ? id : null;
}

/**
 * Creates a row in `projects` (server uses service role). The new row’s `id` is generated by Postgres
 * (uuid) and returned so the client can fill the Project ID field.
 *
 * Requires a real `auth.users` id: set **SCRIPTFLOW_DEMO_USER_ID** or **SCRIPTFLOW_PROJECT_OWNER_USER_ID**
 * in env (Vercel + local).
 */
export async function createNewProjectAction(input?: {
  title?: string;
  userId?: string;
}): Promise<ActionResult<{ projectId: string }>> {
  const userId =
    (input?.userId?.trim() && isValidUuid(input.userId.trim()) ? input.userId.trim() : null) ??
    resolveProjectOwnerUserId();
  if (!userId) {
    console.log(
      "[CREATE PROJECT EXIT EARLY]",
      "missing or invalid SCRIPTFLOW_DEMO_USER_ID / SCRIPTFLOW_PROJECT_OWNER_USER_ID"
    );
    return {
      success: false,
      error:
        "Server missing SCRIPTFLOW_DEMO_USER_ID or SCRIPTFLOW_PROJECT_OWNER_USER_ID (a valid Supabase Auth user UUID). Add one in Supabase Auth → Users, then set the env var on Vercel / .env.local.",
    };
  }
  return createProjectAction({
    title: input?.title?.trim() || "New project",
    userId,
    language: "zh",
  });
}

/**
 * @deprecated Use createNewProjectAction — kept for older imports.
 */
export async function createDemoProjectAction(input?: {
  title?: string;
}): Promise<ActionResult<{ projectId: string }>> {
  return createNewProjectAction(input);
}

